name: Scheduler
on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo display time
        run: echo "The current time is $(date)"
      
